#!/bin/bash

source $(dirname "$0")/common-functions

OLDVERSION=$(get_version)
BUILDSTATUS=$2
PACKAGENAME=$3

echo "Currently on version $OLDVERSION"

if [ -z "$1" ]; then
        echo "Please provide $PROJECTNAME version"
	echo
	cd $PROJECTPATH/versions/
	git branch -rv |cut -f2- -d\/
        exit 1
fi

VERSION=$1

if [[ "$VERSION" == "save" ]]; then
	echo "Saving changes to version: $OLDVERSION"
fi

$(dirname "$0")/checkbuilds all md $BUILDSTATUS $PACKAGENAME > $PROJECTPATH/versions/README.md

mkdir -p /opt/eda-rpm/versions/eda-rpm

cd $PROJECTPATH/versions/
git add $PROJECTPATH/versions/PYTHON
git add $PROJECTPATH/versions/README.md
git add $PROJECTPATH/versions/deps
git add $PROJECTPATH/versions/logs
git add $PROJECTPATH/versions/$PROJECTPACKAGENAME

echo "Publishing Package build changes"
git commit -qam "Publishing build changes for version: `cat $PROJECTPATH/working-version`" &> /dev/null 
git push &> /dev/null

if [[ "$VERSION" == "save" ]]; then
	exit 0
fi

if [[ `git branch |grep $VERSION | wc -l` -gt 0 ]]; then
	git checkout $VERSION
	VERSIONEXISTS=1
else
	echo "Version $VERSION hasn't been generated yet"
	VERSIONEXISTS=0
fi

cd $PROJECTPATH/$PROJECTNAME/

git checkout -q devel
git pull -q

if [ `git tag |grep $TAGPREFIX$VERSION` ]; then
        git -c advice.detachedHead=false checkout $TAGPREFIX$VERSION
	echo "Version changed to: $VERSION"
	if [[ $VERSIONEXISTS == 0 ]];then
		echo "Creating New Version"
		cd $PROJECTPATH/versions/
		git switch --orphan $VERSION
		touch $PROJECTPATH/versions/VERSION-$VERSION
		git add $PROJECTPATH/versions/VERSION-$VERSION
		git commit -am "Created version: $VERSION"
		git push --set-upstream origin $VERSION
	fi
else
        echo "Version $VERSION doesn't exist"
	VERSION=$OLDVERSION
	cd $PROJECTPATH/versions/
	git checkout -q $VERSION
fi

cd $PROJECTPATH/versions/
git push origin -q --all

echo "$VERSION" > $PROJECTPATH/working-version

mock --scrub=all
