#!/bin/bash

source $(dirname "$0")/common-functions

if [[ "$1" != "force" ]]; then
        NEWVERSION=$2
        FROMVERSION=$1
else
	NEWVERSION=$3
	FROMVERSION=$2
fi

cd $PROJECTPATH/versions/

if [ -z "$FROMVERSION" ]; then
	echo "Existing version not defined"
	echo "Select from:"
	echo
	cd $PROJECTPATH/versions/
        git branch -rv |cut -f2- -d\/
        exit 1
fi

if [[ `git branch -rv |cut -f2- -d\/ |grep $FROMVERSION | wc -l` -gt 0 ]]; then
        git checkout $FROMVERSION
else
        echo "Source version $FROMVERSION doesn't exists"
        exit 1
fi

if [ -z "$NEWVERSION" ]; then
        echo "Please provide New $PROJECTNAME version"
        echo "Select from"
	echo
        cd $PROJECTPATH/$PROJECTNAME/
        git ls-remote --tags origin | cut -f3- -d\/ |grep -v "{}" |sort -Vr
	#git branch -rv |cut -f2- -d\/
        exit 1
fi

if [[ "`cd $PROJECTPATH/$PROJECTNAME/ && git ls-remote --tags origin | cut -f3- -d\/ |grep -v "{}" | grep -x $NEWVERSION |wc -l`" != "1" ]]; then
	echo "Version: $NEWVERSION doesn't exist"
	exit 1
fi

rm -rf $PROJECTPATH/migration
mkdir -p $PROJECTPATH/migration/{source,orig,conf,patch,$PROJECTPACKAGENAME}
cp -ar $PROJECTPATH/versions/deps/extra-sources $PROJECTPATH/migration
if [ -f $PROJECTPATH/versions/PYTHON ];then
	cp $PROJECTPATH/versions/PYTHON $PROJECTPATH/migration
fi
mkdir -p $PROJECTPATH/rpmbuilds/$NEWVERSION/SOURCES/
cp $PROJECTPATH/versions/deps/extra-sources/* $PROJECTPATH/rpmbuilds/$NEWVERSION/SOURCES/
cp $PROJECTPATH/versions/PYTHON $PROJECTPATH/migration/
if [ -d $PROJECTPATH/versions/$PROJECTPACKAGENAME ]; then
	for i in `ls $PROJECTPATH/versions/$PROJECTPACKAGENAME/*-$FROMVERSION | xargs -n 1 basename`;do
		FILENAME=$(echo $i | sed "s/-$FROMVERSION/-$NEWVERSION/g")
		cp $PROJECTPATH/versions/$PROJECTPACKAGENAME/$i $PROJECTPATH/migration/$PROJECTPACKAGENAME/$FILENAME
	done
fi

cp -a $PROJECTPATH/versions/deps/*.spec $PROJECTPATH/migration/source/
rm -f $PROJECTPATH/migration/source/$PROJECTPACKAGENAME*
for i in `ls $PROJECTPATH/migration/source/`;do
	if [ -f $PROJECTPATH/versions/deps/original/$i ];then
		cp $PROJECTPATH/versions/deps/original/$i $PROJECTPATH/migration/orig/
	else
		cp $PROJECTPATH/migration/source/$i $PROJECTPATH/migration/orig/
	fi
done
cp -a $PROJECTPATH/versions/deps/*.conf $PROJECTPATH/migration/conf/

cd $PROJECTPATH/migration/

for i in `ls $PROJECTPATH/migration/source/`;do

	NAME=$(echo $i |cut -f1 -d.)
	diff --ignore-all-space -uNr orig/$i source/$i > $PROJECTPATH/migration/patch/$NAME.patch

done

find $PROJECTPATH/migration/patch/ -type f -empty -delete

cp $PROJECTPATH/versions/deps/{extra-deps.txt,remove-deps.txt,rhel-deps.txt} $PROJECTPATH/migration/

cd $PROJECTPATH/versions/

git switch --orphan $NEWVERSION

if [ -f $PROJECTPATH/migration/PYTHON ]; then
        cp $PROJECTPATH/migration/PYTHON $PROJECTPATH/versions/PYTHON
fi

mkdir -p $PROJECTPATH/versions/deps

touch $PROJECTPATH/versions/VERSION-$NEWVERSION

git add $PROJECTPATH/versions/*

git commit -qam "Created Version $NEWVERSION"

git push -u origin $NEWVERSION

$PROJECTPATH/scripts/changeversion $NEWVERSION

$PROJECTPATH/scripts/pypi2spec
for i in `cat $PROJECTPATH/migration/extra-deps.txt`; do

	PACKAGENAME=$(echo $i | cut -f1 -d=)
	VERSION=$(echo $i | cut -f3 -d=)
	
	echo "Adding package $PACKAGENAME $VERSION"
	if [[ "$PACKAGENAME" == "$VERSION" ]];then
		$PROJECTPATH/scripts/addpackage $PACKAGENAME nobuild
	else 
		$PROJECTPATH/scripts/addpackage $PACKAGENAME $VERSION nobuild
	fi

done

cp $PROJECTPATH/migration/remove-deps.txt $PROJECTPATH/versions/deps/remove-deps.txt
cp $PROJECTPATH/migration/rhel-deps.txt $PROJECTPATH/versions/deps/rhel-deps.txt
cp -ar $PROJECTPATH/migration/extra-sources $PROJECTPATH/versions/deps/
cp $PROJECTPATH/migration/PYTHON $PROJECTPATH/versions/PYTHON
mkdir -p $PROJECTPATH/versions/$PROJECTPACKAGENAME
cp $PROJECTPATH/migration/awx-rpm/* $PROJECTPATH/versions/$PROJECTPACKAGENAME/

for i in `cat $PROJECTPATH/migration/remove-deps.txt $PROJECTPATH/migration/rhel-deps.txt`; do
	PACKAGENAME=$(echo $i | sed "s/python//g" | sed "s/python3//g")
	echo "Removing package $PACKAGENAME"
	rm -f $PROJECTPATH/versions/deps/*$PACKAGENAME.spec
	rm -f $PROJECTPATH/versions/deps/*$PACKAGENAME.conf
	rm -f $PROJECTPATH/versions/deps/original/*$PACKAGENAME.spec
        rm -f $PROJECTPATH/versions/deps/original/*$PACKAGENAME.conf
done

cd $PROJECTPATH/versions/
git add $PROJECTPATH/versions/*
git commit -qam "Imported from version $FROMVERSION to version $NEWVERSION"
git push

$PROJECTPATH/scripts/getsources

echo "Applying patches from version: $FROMVERSION"

$PROJECTPATH/scripts/applypatches

