#!/bin/bash

source $(dirname "$0")/common-functions

VERSION=$(get_version)

echo "Generating SPECs for version $VERSION"

PACKAGE=$1
PACKAGEVERSION=$2

cd $PROJECTPATH/awx/

git stash
git checkout -f -q devel
git pull -q

if [ `git tag |grep $VERSION` ]; then
	git -c advice.detachedHead=false checkout -q $VERSION
else
	echo "Version $VERSION doesn't exist"
	exit 1
fi

mkdir -p $PROJECTPATH/versions/deps

cat $PROJECTPATH/awx/requirements/requirements.txt | grep -v "#" > $PROJECTPATH/versions/deps/requirements.txt

cd $PROJECTPATH/versions/deps/
mkdir -p $PROJECTPATH/versions/deps/original
if [[ $PACKAGE == "" ]];then
	for i in `cat $PROJECTPATH/versions/deps/requirements.txt | sed 's/\[.*\]//'`;do 
		PACKAGE=$(echo $i | cut -f1 -d"=") 
		PACKAGEVERSION=$(echo $i | cut -f3 -d"=")
		echo "Generating SPEC-file for $PACKAGE version $PACKAGEVERSION"
		pyp2spec -p 3.11 --license gpl -v $PACKAGEVERSION $PACKAGE 
		cp $PROJECTPATH/versions/deps/*$PACKAGE.spec $PROJECTPATH/versions/deps/*$PACKAGE.conf $PROJECTPATH/versions/deps/original/
	done
else
        if [[ $PACKAGEVERSION == "" ]];then
		echo "Generating SPEC-file for $PACKAGE"
        	pyp2spec -p 3.11 --license gpl $PACKAGE
		cp $PROJECTPATH/versions/deps/*$PACKAGE.spec $PROJECTPATH/versions/deps/*$PACKAGE.conf $PROJECTPATH/versions/deps/original/
	else
		echo "Generating SPEC-file for $PACKAGE version $PACKAGEVERSION"
	        pyp2spec -p 3.11 --license gpl -v $PACKAGEVERSION $PACKAGE
		cp $PROJECTPATH/versions/deps/*$PACKAGE.spec $PROJECTPATH/versions/deps/*$PACKAGE.conf $PROJECTPATH/versions/deps/original/
	fi
fi


